In [2]:
import numpy as np
import igl

In [29]:
v1 =np.array([[0,3,4],[1,8,0],[0,-1,9]])

In [27]:
height = np.max(v1[:,2])/3
ne = 0.1
for i in (range(3)):
    #idiam = np.where(v1[:,2] == 0)
    idiam = np.where((v1[:,2] < i*height + ne) & (v1[:,2] > i*height-ne))
            #dist = x=igl.all_pairs_distances(v1[idiam],v1[idiam],False)
            #diam.append(np.max(dist))
    print(idiam)

(array([1]),)
(array([], dtype=int64),)
(array([], dtype=int64),)


In [45]:
maxr = np.max(v1[:,1])
irmax = np.where(v1[:,1] == maxr)
v1[irmax]

array([[1, 8, 4]])

In [70]:
v1 = np.array([[0.0,3.0,4.0],[1.0,8.0,4.0],[0.0,-1.0,9.0]])

In [71]:
print(type(v1))
x=igl.all_pairs_distances(v1,v1,False)
print(x)

<class 'numpy.ndarray'>
[[ 0.          5.09901951  6.40312424]
 [ 5.09901951  0.         10.34408043]
 [ 6.40312424 10.34408043  0.        ]]


In [74]:
np.max(x)

10.344080432788601